language:
  node_js
node_js:
  - 12
services:
  - mongodb
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.19.2-1
cache:
  yarn: true
install:
  - npm install -g codecov
  - cd server
  - yarn install --check-files
  - yarn add dotenv
script:
  - yarn test